/**
 * @author Stavros Labrinos [stalab at linuxmail.org] on 28/01/21.
 */

export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_FAIL = 'FETCH_CITY_FAIL';

export const FETCH_CONDITIONS = 'FETCH_CONDITIONS';
export const FETCH_CONDITIONS_START = 'FETCH_CONDITIONS_START';
export const FETCH_CONDITIONS_SUCCESS = 'FETCH_CONDITIONS';
export const FETCH_CONDITIONS_FAIL = 'FETCH_CONDITIONS';

export const SET_FORECAST_TO_DISPLAYING_CONDITIONS = 'SET_FORECAST_TO_DISPLAYING_CONDITIONS';
export const SET_CURRENT_TO_DISPLAYING_CONDITIONS = 'SET_CURRENT_TO_DISPLAYING_CONDITIONS';

export const FETCH_INPUT_CITY_CONDITIONS_START = 'FETCH_INPUT_CITY_CONDITIONS_START';
export const FETCH_INPUT_CITY_CONDITIONS_SUCCESS = 'FETCH_INPUT_CITY_CONDITIONS_SUCCESS';
export const FETCH_INPUT_CITY_CONDITIONS_FAIL = 'FETCH_INPUT_CITY_CONDITIONS_FAIL';

export const SET_FORECAST_TO_DISPLAY = 'SET_FORECAST_TO_DISPLAY';
export const SET_CURRENT_TO_DISPLAY = 'SET_CURRENT_TO_DISPLAY';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_CITIES_COLLECTION_START = 'FETCH_CITIES_COLLECTION_START';
export const FETCH_CITIES_COLLECTION_SUCCESS = 'FETCH_CITIES_COLLECTION_SUCCESS';
export const FETCH_CITIES_COLLECTION_FAIL = 'FETCH_CITIES_COLLECTION_FAIL';
export const CLEAR_CITIES_COLLECTION = 'CLEAR_CITIES_COLLECTION';